### ISSUE TITLE
support file bundling in splitHTML and rejoinHTML

### ISSUE THREAD

**Issue by FredKSchott** [Polymer/polymer-build#106]
Closure compiler and others output a single file from many. @azakus would like to compile all the javascript together and rejoin the bundled into the shell (this only makes sense for a bundled build).

@azakus can you share the workaround you created to get this working in the current version of polymer-build?

**Comment by azakus** [comment]
You can see this in my branch https://github.com/Polymer/polymer/tree/2.0-closure

**Comment by jordanaustin** [comment]
Any progress on this? The branch that @azakus pointed to doesn't seem to exist anymore. 

I thought that I could use the splitter, and bundle the js, as we could with Vulcanize, but that doesn't seem to work as I thought. Maybe I'm doing something wrong?

**Comment by ronnyroeller** [comment]
Same problem here. Any advice how to bundle the JS into a single file?

**Comment by justinfagnani** [comment]
This is being done in https://github.com/Polymer/polymer-bundler/pull/620
