### ISSUE TITLE
Add clean build directory

### ISSUE THREAD

**Issue by chuckh** [Polymer/polymer-build#11]
### Description
Before build starts should clean the build directory.  This way artifacts from previous builds will be removed.

#### Example
Could add to https://github.com/Polymer/polymer-build/blob/master/test/test-project/gulpfile.js#L28

```
const del = require('del');

// Clean build directory
gulp.task('clean', () => {
  return del(['build/**','!build']);
});

gulp.task('default',['clean'], (cb) => {
   ...
```

**Comment by FredKSchott** [comment]
Agreed, this shouldn't be a responsibility of polymer-build (well-known libraries like `del` already exist to do this) but it is a best practice to clean before build and this should be reflected in the test-project gulpfile.

PRs welcome! :)
