### ISSUE TITLE
TypeError: this.config.isSource is not a function

### ISSUE THREAD

**Issue by tony19** [Polymer/polymer-build#123]
### Description
Running the `gulpfile.js` from `generator-polymer-init-custom-build` with `polymer-build` fails.

### Versions & Environment
- polymer-build: 0.7.1
- node: 7.5.0
- Operating System: macOS Sierra 10.12

#### Steps to Reproduce

 1. Clone https://github.com/tony19-sandbox/polymer-build-issue-88.git
 2. In newly created directory, run:

         npm install
         bower install
         gulp build

 3. Observe an error.

#### Expected Results
The build completes without error.

#### Actual Results
Failure:
```shell
$ gulp build
warn:    "sourceGlobs" config option has been renamed to "sources" and will no longer be supported in future versions
warn:    "includeDependencies" config option has been renamed to "extraDependencies" and will no longer be supported in future versions
[22:52:17] Using gulpfile ~/src/polymer/polymer-build-issue-88/gulpfile.js
[22:52:17] Starting 'build'...
Deleting build directory...
Analyzing build dependencies...
(node:54245) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 52): TypeError: this.config.isSource is not a function
(node:54245) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by tony19** [comment]
Deleting `node_modules` and reinstalling seems to have cleared the issue.

**Comment by FredKSchott** [comment]
i'm surprised that this wasn't updated along with polymer-build during npm install. I'll keep an eye on this

**Comment by tony19** [comment]
@FredKSchott Updated description with more reliable steps. This issue occurs when manually updating `polymer-cli` to use `polymer-build` 0.7.1 (as listed in the steps to reproduce).

When manually installing `polymer-build` 0.7.1 inside `node_modules/polymer-cli`, `polymer-project-config` 1.2.0 is correctly installed inside `node_modules/polymer-cli/node_modules/polymer-build/node_modules`, but `polymer-cli` has its own dependency on `polymer-project-config` at 1.1.0. I'm assuming `polymer-build` defers to the 1.1.0 version found at the `polymer-cli` level instead of the one in its own `node_modules`; and that's why installing it explicitly alongside `polymer-build` resolves the issue.
