### ISSUE TITLE
Bundler missing semicolons

### ISSUE THREAD

**Issue by msc117** [Polymer/polymer-build#137]
### Description
Upgrading to polymer build from vulcanize is causing semicolons to not be placed correctly causing paper element styling to be off

### Versions & Environment
- polymer-build: 2.0.0-pre.6
- node: 7.5.0
- Operating System: macOS 10.12.3

#### Steps to Reproduce
```html
<link rel="import" href="../../bower_components/font-roboto/roboto.html">
<link rel="import" href="../../bower_components/paper-button/paper-button.html">
<link rel="import" href="../../bower_components/paper-dialog/paper-dialog.html">
<link rel="import" href="../../bower_components/paper-dialog-scrollable/paper-dialog-scrollable.html">
<link rel="import" href="../../bower_components/paper-card/paper-card.html">
<link rel="import" href="../../bower_components/paper-input/paper-input.html">
<link rel="import" href="../../bower_components/paper-input/paper-textarea.html">
<link rel="import" href="../../bower_components/paper-toolbar/paper-toolbar.html">
<link rel="import" href="../../bower_components/paper-badge/paper-badge.html">
<link rel="import" href="../../bower_components/paper-styles/paper-styles.html">
<link rel="import" href="../../bower_components/paper-radio-group/paper-radio-group.html">
<link rel="import" href="../../bower_components/paper-toggle-button/paper-toggle-button.html">
<link rel="import" href="../../bower_components/iron-icons/iron-icons.html">
<link rel="import" href="../../bower_components/iron-icons/social-icons.html">
<link rel="import" href="../../bower_components/iron-icons/av-icons.html">
<link rel="import" href="../../bower_components/iron-pages/iron-pages.html">
<link rel="import" href="../../bower_components/paper-spinner/paper-spinner.html">
<link rel="import" href="../../bower_components/neon-animation/neon-animations.html">
<link rel="import" href="../../bower_components/paper-checkbox/paper-checkbox.html">
<link rel="import" href="../../bower_components/paper-drawer-panel/paper-drawer-panel.html">
<link rel="import" href="../../bower_components/paper-fab/paper-fab.html">
<link rel="import" href="../../bower_components/paper-toast/paper-toast.html">
<link rel="import" href="../../bower_components/paper-header-panel/paper-header-panel.html">
<link rel="import" href="../../bower_components/iron-flex-layout/iron-flex-layout-classes.html">
<link rel="import" href="../../bower_components/paper-date-picker/paper-date-picker.html">
<link rel="import" href="../../bower_components/paper-dropdown-menu/paper-dropdown-menu.html">
<link rel="import" href="../../bower_components/paper-listbox/paper-listbox.html">
<link rel="import" href="../../bower_components/paper-item/paper-item.html">
<link rel="import" href="../../bower_components/paper-header-panel/paper-header-panel.html">
<link rel="import" href="../../bower_components/gold-cc-input/gold-cc-input.html">
<link rel="import" href="../../bower_components/gold-cc-cvc-input/gold-cc-cvc-input.html">
<link rel="import" href="../../bower_components/gold-cc-expiration-input/gold-cc-expiration-input.html">
<link rel="import" href="../../bower_components/gold-zip-input/gold-zip-input.html">

```

#### Expected Results
No file diff between vulcanized.html and newly generated polymer-build.html

#### Actual Results
Lots of diffs where semicolon is missing before `@apply` CSS mixin.
E.g.
`center;-webkit-transform:scale3d(0,1,1);transform:scale3d(0,1,1);@apply(--paper-input-container-underline-focus)}.underline.is-highlighted`
`center;-webkit-transform:scale3d(0,1,1);transform:scale3d(0,1,1) @apply(--paper-input-container-underline-focus)}.underline.is-highlighted`

**Comment by rictic** [comment]
It's a bug on us either way, but one thing to check: what happens if you remove the parens after the `@apply`? The parens syntax is deprecated, and it's possible that the css printer doesn't handle it properly.

**Comment by msc117** [comment]
Since these are from paper elements, I don't have control over the CSS. 

The issue may not be from your project, actually. I think it broke from the `3.3.3` update for the [html minifier|https://github.com/kangax/html-minifier] I'm using to minify the resulting built html file. 

When I remove the minifyCss option
```javascript
let minifiedHtml = minify.minify(html, {
    customAttrAssign: [/\$=/],
    removeComments: true,
    removeCommentsFromCDATA: true,
    removeCDATASectionsFromCDATA: true,
    collapseWhitespace: true,
    collapseInlineTagWhitespace: true,
    removeScriptTypeAttributes: true,
    removeStyleLinkTypeAttributes: true,
    minifyJS: true,
   //  minifyCSS: true,
});
```

I don't see the styling issues. This isn't a valid workaround however, since I need the whole file minified. Any ideas for how I can fully minify the outputted file from polymer build?

**Comment by web-padawan** [comment]
@msc117 this should be alreadybfixed by `clean-css` which is used by `html-minifier`.

**Comment by msc117** [comment]
Have you tried with the latest `3.3.3` release for `html-minifier`? Because that seems to be where my problems are coming from. On `3.3.3` with `polymer-build` rather than `vulcanize` and `3.3.2` I'm having the issue as described.

**Comment by msc117** [comment]
Yep, it was grabbing `4.0.1` for some reason. Thanks! I can close this issue if okay

**Comment by rictic** [comment]
Nice catch @tony19! Agreed that this looks like https://github.com/jakubpawlowicz/clean-css/issues/874

Closing!
