### ISSUE TITLE
"entrypoint" file should not necessarily be precached by generated SW

### ISSUE THREAD

**Issue by keanulee** [Polymer/polymer-build#140]
In News, the entrypoint file that _should_ be specified in polymer.json is "index.html". Currently, it is "/" because we don't want the generated SW to precache "/index.html" (since we don't consider that to be a valid URL - we serve the _contents_ of "index.html" for the path "/", but the path "/index.html" would be incorrectly consumed by our client-side router).

cc @justinfagnani @frankiefu

**Comment by mgibas** [comment]
I have related issue: since index.js is precached I can not utilize file revisions and make browser to get new files :disappointed:

**Comment by FredKSchott** [comment]
Ah, that's really unfortunate. The way we work with `sw-precache-config.js` is additive, so not sure if this is possible at the moment.

I actually can't think of a good reason to cache the entrypoint to `index.html`, since it's job is to be returned for `/` and an infinite number of other URLs. I think it makes sense to stop caching by default, @justinfagnani wdyt?

**Comment by justinfagnani** [comment]
I think we don't always want to provide a route for `index.html`, but we do want to cache the contents of it so that we can return it for the fallback content.

@keanulee is there a problem with just specifying `index.html` as the entrypoint and having the router reject that?

**Comment by keanulee** [comment]
@justinfagnani `index.html`as the entrypoint is _possible_, but it's a limitation since 1) it doesn't really play well with `app-route` and 2) means that it's not possible to have "clean" routes without file extensions (e.g. `/`)

**Comment by justinfagnani** [comment]
@keanulee why would that prevent clean routes? The router would not support index.html

**Comment by keanulee** [comment]
I think I misread your previous comment, so ignore my last comment.

From the `polymer-build` point of view, "index.html" is the starting point for analysis, so it makes sense for "index.html" to be the entrypoint in polymer.json. However, from the SW/browser point of view, only the "/" URL is valid, and the contents of "index.html" should be cached there. So I'm saying the generated SW shouldn't try to fetch the URL "index.html" that is read from polymer.json.

**Comment by justinfagnani** [comment]
I may need to see the errors with what I'm suggesting directly, but it seems like you do actually want to cache index.html and use that as your navigateFallback.

What specific problem was happening with entrypoint and navigateFallback set to `index.html`?

**Comment by keanulee** [comment]
If I do that with `Polymer/news#master`, the generated `service-worker.js`precaches both "/" and "/index.html" (which means 2 requests and 2 cache entries for the same file), but I only really want to precache "/". I don't specify "index.html" in `sw-precache-config.js`, but polymer build adds to it.

```js
var precacheConfig = [["/","1603a3707bb646fd55dbbb30baa6a7a6"], /* ... */,["/index.html","b31b352d85676aa55d0e95f1b6eb2b1a"], /* ... */];
```

**Comment by CaptainCodeman** [comment]
I'd love to have a "leave sw-precache alone completely" option for when you want complete control over it but are otherwise happy with the polymer-cli build tooling. i.e. just use the sw-precache-config.js file I've configured as-is.

**Comment by CaptainCodeman** [comment]
Shouldn't it really use something like:

```
dynamicUrlToDependencies: {
  '/': ['index.html']
},
```

https://github.com/GoogleChrome/sw-precache#dynamicurltodependencies-objectstringarraystring

**Comment by keanulee** [comment]
@CaptainCodeman That's exactly what News does in sw-precache-config.js https://github.com/Polymer/news/blob/master/sw-precache-config.js#L8

**Comment by FredKSchott** [comment]
@CaptainCodeman I can't remember if we already discussed this in a separate thread, but if you want to use sw-precache directly instead of the `polymer-build` wrapper you can always do that.

**Comment by justinfagnani** [comment]
I think we figured out that the main entrypoint really should be `index.html`, and that the service worker config needs to specify `index.html` as the fallback so that `/` will route to it. Writing that is covered in #636, so closing this now.
