### ISSUE TITLE
Compilation targets incorrect files

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer-build#147]
This occurs in the @next version.

* The compiled "bundled" output does not compile output for the entry points
* The compiled "unbundled" output compiles `webcomponents-es5-loader.js`. This is problematic because the loader contains ES6 code which should not be compiled. Adding an "exclude" option for files to compile could address this.

**Comment by web-padawan** [comment]
>  the loader contains ES6 code which should not be compiled
So how shall we use it with Safari 9 and IE?

**Comment by FredKSchott** [comment]
`webcomponents-es5-loader.js` includes a shim for the ES6 features needed in those browsers, because "According to the spec, Custom Elements must be ES6 classes".  (https://github.com/webcomponents/webcomponentsjs#webcomponents-es5-loaderjs)

**Comment by FredKSchott** [comment]
This was fixed in https://github.com/Polymer/polymer-cli/pull/592
