### ISSUE TITLE
build should include correct version of web-components polyfills

### ISSUE THREAD

**Issue by sorvell** [Polymer/polymer-build#150]
So user don't have to deal with this, build output should fix use of the `webcomponents-loader.js` when possible.

* ES5 compiled builds require `webcomponents-es5-loader.js` to function correctly on all browsers.
* Uncompiled builds should use `webcomponents-loader.js`.

**Comment by tony19** [comment]
I think this is resolved by https://github.com/Polymer/polymer-cli/pull/598

**Comment by FredKSchott** [comment]
@tony19 thanks for updating, this was fixed in the most recent `next` release on npm: `npm install -g polymer-cli@next`
