### ISSUE TITLE
 how to bundle Roboto web font?

### ISSUE THREAD

**Issue by cordovapolymer** [Polymer/polymer-build#155]
How to instruct polymer build to bundle Roboto and other external resources?
In polymer starter kit 1.0 gulp copy task has been doing this.

**Comment by cordovapolymer** [comment]
@rictic bump!

**Comment by mgibas** [comment]
U can use `extraDependencies` in `polymer.json`. Thats how
```json
    "manifest.json",
    "bower_components/webcomponentsjs/webcomponents-lite.min.js"
```
are copied to output folder.

**Comment by FredKSchott** [comment]
Yup, see the note on `extraDependencies` in the README: https://github.com/Polymer/polymer-build#projectdependencies

**Comment by cordovapolymer** [comment]
@mgibas @FredKSchott 
I'm talking about https://github.com/Polymer/font-roboto , I include it with `<link rel="import">` and it loads the font from google servers. I don't see how extraDependencies are releted to this polymer element.

**Comment by web-padawan** [comment]
@cordovapolymer use `font-roboto-local` if you need to have fonts served from your project. `polymer-build` doesn't bundle external resources, and unlikely to be able to.

**Comment by cordovapolymer** [comment]
@web-padawan thanks!
