### ISSUE TITLE
[Feature Request] Allow to configure minEntrypoints passed to generateShellMergeStrategy

### ISSUE THREAD

**Issue by web-padawan** [Polymer/polymer-build#165]
As @usergenic said ealirer [here](https://github.com/Polymer/polymer-build/pull/108#discussion_r96712278), adding configuration option for [this line](https://github.com/Polymer/polymer-build/blob/master/src/bundle.ts#L78) should be separate PR, but is probably worth looking at soon.

Do you have any plans about this? Is it a future work after releasing `polymer-build` 1.0.0 ?

I'm interested in this stuff because of my experience with a large project. There are lots of dependencies only required by 2 fragments, but as of now, they are all being bundled into the shell. Thanks to libraries like `ace` and `moment` (without locales), our shell JS bundle is more than 300 K minified and gzipped, even though we try to lazy load as much as we can.

Related to https://github.com/Polymer/polymer-bundler/issues/437

**Comment by justinfagnani** [comment]
@usergenic we'll need this added to the project config and CLI too.

**Comment by usergenic** [comment]
@justinfagnani I'm not sure it makes sense to add the minEntrypoints directly to the config.  I think it makes more sense to have the user provide the argument like this in their gulp-file:
```js
.pipe(project.bundle({strategy: generateShellMergeStrategy('shell.html', 3)}))
```

That would work with https://github.com/Polymer/polymer-build/pull/189

**Comment by usergenic** [comment]
polymer-build 1.2.0 published 🎉
