### ISSUE TITLE
Prevent from adding `html`, `body`, `head` tags to the rejoined file.

### ISSUE THREAD

**Issue by myuseringithub** [Polymer/polymer-build#173]
require('polymer-build').HtmlSplitter adds `html, head, body` tags, which causes issues for my app. 

Example: 
A file
``` <h1>Hello</h1> ```
becomes
``` <html><head></head><body><h1>Hello</h1></body></html>```

## How to prevent this behavior ?

**Comment by myuseringithub** [comment]
I think your tool for splitting `HTML`, then using conditionals to target the specific parts is amazing, and shouldn't be limited to webcomponents structures only. 
Personally I would like to use it for html files that contain inline scripts (`<script>` tags), and apply custom transpilation and minification on these tags. 
It could be further developed for recognizing custom tags/attributes, and ability to target specific custom parts in the documents.
Thanks

**Comment by rictic** [comment]
The fix in code is for us to notice pars5.ASTNodes without locations. These are nodes that were hallucinated by the HTML5 parsing algorithm. ParsedHtmlDocument#stringify in the analyzer handles this, might be able to use that. Or could just copy `removeFakeNodes` here (though note that it mutates the document, so only use it on a non-shared document, or use the `clone` library): https://github.com/Polymer/polymer-analyzer/blob/master/src/html/html-document.ts#L205-L217

**Comment by myuseringithub** [comment]
@usergenic  I wonder if the release in 

- https://www.npmjs.com/package/polymer-build

- https://github.com/Polymer/polymer-build

are the same. Because when installing through NPM repository it installs the version v1.1.0 which matches the fix, but in node_modules the file doesn't have the merged code. 
Releases are not synchronous ?
 Thanks for the fix.

**Comment by rictic** [comment]
Reopening to track investigation

**Comment by abdonrd** [comment]
The #185 was merged after the v1.1.0. It's on `master`.

**Comment by myuseringithub** [comment]
Now its working. Before I needed to npm install directly from `github:polymer/polymer-build`, and them build the module manually (npm install; npm run build).

**Comment by myuseringithub** [comment]
@abdonrd I'm sorry for closing it to early. I did a clean npm install (where package.json has `"polymer-build": "^1.1.0"`), and the versions aren't the same between NPM repo and Github (although both refer to 1.1.0). I will let you close the issue after verifying. 

The only way I got it to work is installing it directly from Github:
- `npm install --save github:polymer/polymer-build`
- `cd ./node_modules/polymer-build; npm install; npm run build;`

**Comment by abdonrd** [comment]
That is because the #185 was merged after the v1.1.0. You have to wait for the Polymer Team release a new version.

**Comment by myuseringithub** [comment]
Oh, now I see. The master branch is different from the latest release (v1.1.0). Thanks

**Comment by s2tephen** [comment]
Any idea of when the new release is going to be published to npm?

**Comment by usergenic** [comment]
@s2tephen hoping to get a release of build out after https://github.com/Polymer/polymer-build/pull/189 lands, preferably by/on Monday, Apr 24.

**Comment by usergenic** [comment]
polymer-build 1.2.0 published 🎉
