### ISSUE TITLE
Can we expose the bundler `strategy` and `mapper` options when providing the BuildBundler Transform stream?

### ISSUE THREAD

**Issue by usergenic** [Polymer/polymer-build#178]
If a user wanted to customize the strategy or mapper for their build (see the `generateManifest` method of `polymer-bundler` https://github.com/Polymer/polymer-bundler/blob/master/src/bundler.ts#L164), could we provide options to pass these in?

**Comment by justinfagnani** [comment]
This should take options: https://github.com/Polymer/polymer-build/blob/master/src/polymer-project.ts#L59

**Comment by usergenic** [comment]
https://github.com/Polymer/polymer-build/pull/189 fixes this.

**Comment by usergenic** [comment]
polymer-build 1.2.0 published 🎉
