### ISSUE TITLE
Use less intrusive gambit for removing es5 adapter

### ISSUE THREAD

**Issue by kevinpschaaf** [Polymer/polymer-build#200]
### Description
The [current gambit](https://github.com/Polymer/polymer-build/blob/master/src/custom-elements-es5-adapter.ts#L112-L122) for removing the es5 adapter script on browsers without native `customElements` (wrap scripts with with `<div>` and remove div in feature detection script) to prevent the script from erroring on non-ES6 compliant browsers requires moving user scripts/links from head to body (to accommodate the wrapper `<div>`), which is fairly intrusive.

Unfortunately it also exacerbates [an HTML Imports / styling bug](https://bugs.chromium.org/p/chromium/issues/detail?id=719078) in Chrome 58.

Proposed alternate gambit that does not require moving user links around:

```html
<!-- start injected -->
<script>if (!window.customElements) { document.write('<!--'); }</script>  
<script src="/bower_components/webcomponentsjs/custom-elements-es5-adapter.js"></script>
<script>if (!window.customElements) { document.write('-->'); }</script>
<!-- stop injected -->

<script src="/bower_components/webcomponentsjs/webcomponents-loader.js"></script>
```

Mock example: http://jsbin.com/saxade/1/edit?html,console,output

### Versions & Environment
- polymer cli: 0.18.1
- node: v6.10.2
- Operating System: Mac

**Comment by FredKSchott** [comment]
Wouldn't the `document.write('-->')` line be commented out by the `document.write('<!--')` call and never run? Is there a reason to keep it that I'm missing?

**Comment by stramel** [comment]
I believe you are right @FredKSchott. Looks like it is ending on `document.write('-->` and then outputting `') }`

**Comment by FredKSchott** [comment]
@stramel oh yea of course, that's even worse. 
The submitted change/commit leaves that line out.

**Comment by FredKSchott** [comment]
Fixed in https://github.com/Polymer/polymer-build/pull/205
