### ISSUE TITLE
Transform streams for generating Prefetch Links, Push Manifest and Service Workers need re-analysis of changed documents, specifically after Bundling.

### ISSUE THREAD

**Issue by usergenic** [Polymer/polymer-build#203]
Should be able to achieve this in ways similar to the BuildBundler's changed-file check.

Without this re-analysis, these 3 transforms produce bogus output.

**Comment by usergenic** [comment]
Note: Prefetch is currently code inside of polymer-cli -- that should rebuilt here, without all the 
 broken.

**Comment by usergenic** [comment]
oh this is not actually fixed.  unclosing.  nothanks github auto-close!

**Comment by usergenic** [comment]
Fixed as of https://github.com/Polymer/polymer-cli/pull/756

**Comment by usergenic** [comment]
Actually

**Comment by usergenic** [comment]
Not sure about service worker yet.

**Comment by rpapeters** [comment]
Not seeing a server-worker.js file inside build directory, despite having the --add-service-worker option turned on.

**Comment by FredKSchott** [comment]
@usergenic feel free to update labels if necessary
