### ISSUE TITLE
Minor nomenclature changes

### ISSUE THREAD

**Issue by abdonrd** [Polymer/polymer-build#24]
I propose to rename these exposed variables:

- [`swConfig`](https://github.com/Polymer/polymer-build/blob/master/src/service-worker.ts#L25) to `serviceWorkerConfig` to maintain the same nomenclature as `serviceWorkerPath`.

- [`serviceWorkerPath`](https://github.com/Polymer/polymer-build/blob/master/src/service-worker.ts#L24) to `serviceWorkerFilename`. Because the real path is created at [src/service-worker.ts#L113](https://github.com/Polymer/polymer-build/blob/master/src/service-worker.ts#L113) with the `buildRoot` and the filename.

**Comment by FredKSchott** [comment]
swConfig is the config passed to the `sw-precache` library, which is where that name comes from. I don't like swConfig very much either, maybe just `config`? both `sw-` & `serviceWorker-` prefixes are redundent.

-1 for serviceWorkerFilename, since it can still be a path within the build destination (ex: `path/to/dest/service-worker.js`). But maybe based on the above, just `path`? `filePath`?

**Comment by abdonrd** [comment]
Sounds good! :)

```typescript
export interface AddServiceWorkerOptions {
  project: PolymerProject;
  buildRoot: string;
  bundled?: boolean;
  path?: string;
  config?: SWConfig;
}
```

**Comment by FredKSchott** [comment]
love `path`, much simpiler.

Seeing config there confuses me, isn't the whole object a config? maybe `fileConfig`, `serviceWorkerConfig`, `generationConfig`... hmmmm...

**Comment by robdodson** [comment]
feels like swPrecacheConfig would be better...

**Comment by robdodson** [comment]
because, as I understand it, that config object is entirely for the sw-precache library and doesn't have anything to do with polymer-build, right?

**Comment by FredKSchott** [comment]
@robdodson correct, if you pass us `swConfig` we use it instead of a blank object to start, and then apply a few additional properties based on your project before sending it to sw-precache

+1 for swPrecacheConfig, I think that's what we were going for with swConfig but even more clear

**Comment by abdonrd** [comment]
+1 for swPrecacheConfig, like the `sw-precache-config.js` file.
