### ISSUE TITLE
Update polymer-bundler to ^2.1.0

### ISSUE THREAD

**Issue by ankon** [Polymer/polymer-build#244]
polymer-bundler 2.1.0 was released with a fix for https://github.com/Polymer/polymer-bundler/pull/553, which would be great to have.

**Comment by ZoneMR** [comment]
3.0.1 is now out. 3.0.x contains some essential fixes.

**Comment by arturparkhisenko** [comment]
Isn't actual anymore? See: https://github.com/Polymer/polymer-build/blob/master/package.json#L37

**Comment by ankon** [comment]
Seems this was indeed fixed without referencing/updating this issue: https://github.com/Polymer/polymer-build/commit/e43fe0e3f8ad0ccee0e2d51256b33218b2971ad7 (for #248) moved to ^2.2.0, and #252 then moved to ^3.0.1 (and later further). 

Closing.
