### ISSUE TITLE
Polymer build fails when bower_components is called something else

### ISSUE THREAD

**Issue by govis** [Polymer/polymer-build#255]
### Description
My bower install directory is called <code>import</code> as opposed to <code>bower_components</code>. When I run "polymer build" I get  "ENOENT: no such file or directory" error:
<pre></code>error:   Promise rejection: Error: ENOENT: no such file or directory, open '&lt;Project root directory>\bower_components\import\paper-fab\paper-fab.html'
error:   Error: ENOENT: no such file or directory, open '&lt;Project root directory>bower_components\import\paper-fab\paper-fab.html'</code></pre>

My imports are relative like so:
<code>&lt;link rel="import" href="../import/paper-fab/paper-fab.html" /></code> and it seems to be prepending it with <code>bower_components</code> that's unnecessary

### Versions & Environment
- polymer-build: v2.0.0
- node: v8.2.1
- Operating System: Windows 10

#### Steps to Reproduce
Rename bower_components to import

#### Expected Results
No errors

#### Actual Results
"ENOENT: no such file or directory" error

**Comment by govis** [comment]
After some digging it appears to be appending <code>bower_components</code> to relative links that are broken if the first place. I had a few that where off by a level. So the build would've failed anyway with the same error, but the message is quoting an unexpected directory.

It would be useful if  the message also included the source file name that is being parsed that contains the broken link so we don't have to resort to file monitoring tools to troubleshoot errors like this.

Please close as you see fit. Thanks.

**Comment by justinfagnani** [comment]
We translate relative paths out of the package folder to point into the components folder, so that's why `../import` is changed to `./bower_components/import`. We'll be respecting the .bowerrc file in the Analyzer soon with PRs like https://github.com/Polymer/polymer-analyzer/pull/801
