### ISSUE TITLE
Support transpilation of ES modules (both inline and external scripts)

### ISSUE THREAD

**Issue by usergenic** [Polymer/polymer-build#269]
Right now polyserve is the way to run/test code using `<script type=module>` in browsers without module support, because it converts the HTML and JS code on the fly based on browser capabilities.  We need to support the same conversions in `polymer-build`.

To the extent possible we should generalize and extract the transformation code out of polyserve and using the same code in both places.

**Comment by daKmoR** [comment]
any updates on this? would be awesome to be able to use `<script type=module>` in production :)

**Comment by usergenic** [comment]
@daKmoR This is on our short-term roadmap but work hasn't actually started on this item yet.  Aiming for  December.

**Comment by daKmoR** [comment]
sorry for being eager for information but and has there been any process on this?
