### ISSUE TITLE
ES6 minification on Safari 10 (macOS + iOS)-> SyntaxError: Cannot declare a let variable twice: 'a'. 

### ISSUE THREAD

**Issue by pdesjardins90** [Polymer/polymer-build#273]
### Description
Both ES6-unbundled and ES6-bundled presets result in an app that fails at launch on iOS 10, but not on iOS 11. The ES5-bundled preset works fine.

**Error**
SyntaxError: Cannot declare a let variable twice: 'a'. 
(And  a bunch of others which seem to follow this one)

### Versions & Environment
- polymer-build: 2.1.1
- node: 8.9.1
- Operating System: macOS 10.13.1

#### Steps to Reproduce

- `polymer init` -> polymer-starter-kit
- `polymer build`
- `polymer serve` build/es6-unbundled or build/es6-bundled
- Open an iPhone Simulator
- Navigate to localhost:8081, witness the white screen and see console for error

#### Expected Results
No error is thrown and app loads normally, as on iOS 11

#### Actual Results
White screen and a bunch of console errors

**Comment by pdesjardins90** [comment]
More specifically, it has to do with js minification => unminified versions of these presets seem to work

**Comment by pdesjardins90** [comment]
Any news on this? We have to serve an unminified version of our app to customers because of this (26% heavier).

**Comment by czellweg** [comment]
The same issue appears when opened in Safari, for both `build/es6-unbundled` and `build/es6-bundled`. `build/es5-bundled` works fine.

**Comment by pdesjardins90** [comment]
@czellweg Desktop Safari 10?

**Comment by czellweg** [comment]
Yes, desktop Safari 10.1.1. For now, we had to disable js-minification:
```
"builds": [
    {
      "preset": "es6-bundled",
      "js": { "minify" : false }
    }
  ]
```

Not satisfactory of course, yet it'll have to do for now.

**Comment by pdesjardins90** [comment]
As we have. I'll update the title for desktop and mobile

**Comment by justinfagnani** [comment]
This issue was moved to Polymer/polymer-cli#946

**Comment by justinfagnani** [comment]
I moved this because it's the CLI that actually handles minificiation by calling out to Babili.
