### ISSUE TITLE
Changing root causes dependency path lookup to get weird

### ISSUE THREAD

**Issue by robdodson** [Polymer/polymer-build#34]
Per the zip file I shared earlier:

Changing `root` to `src` causes the dependency lookup of `/bower_components/polymer/polymer.html` to turn into `../../../../bower_components/polymer/polymer.html`

Sample output from running `polymer build --verbose`

```
debug:   found shell dependencies
{ shellUrl: 'my-app.html',
  shellUrlDir: '.',
  shellDeps:
   [ '../../../../bower_components/polymer/polymer.html',
```

**Comment by robdodson** [comment]
@FredKSchott any progress on this?

**Comment by FredKSchott** [comment]
*@robdodson & I fixed this in person last week, and the problem stemmed from unexpected path formats in the shell file*

@robdodson anything else needed here?

**Comment by robdodson** [comment]
Don't think so.

**Comment by FredKSchott** [comment]
👍
