### ISSUE TITLE
'gulp build-all' create files in incorrect directory on Windows 10

### ISSUE THREAD

**Issue by hurst** [Polymer/polymer-build#41]
### Description

`gulp build-all` builds files in `./lib/src` instead of `./lib`

### Versions & Environment

- polymer-build: 0.4.1
- node: v4.5.0
- Operating System: Windows 10 Pro (1607) 14393.105

#### Steps to Reproduce
Run `gulp build-all` on Windows (PowerShell, CMD, or Git Bash)

#### Expected Results

Output should be in the `./lib` directory

#### Actual Results

Output is in the `./lib/src` directory. All tests fail with MODULE_NOT_FOUND error.

This does not happen on *nix environments that I've tested.

**Comment by hurst** [comment]
It looks like Windows doesn't calculate the same default option for --rootDir as *nix; maybe a bug in TypeScript but I can't find any open issues on it. Setting `rootDir: "src"` in `tsconfig.json` works for both environments.

**Comment by FredKSchott** [comment]
I can't reproduce / I don't know what project you're trying to build. Can you update your "Steps to Reproduce" to include steps to create your project?

**Comment by hurst** [comment]
Sorry! I realized that might be confusing but haven't been online all day. I've run into a few other issues on Windows involving `gulp test` on polymer-build builds. I'll be sure to make it more clear in future issues.
