### ISSUE TITLE
Promise rejection: TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by rof20004** [Polymer/polymer-build#46]
Here is my error when i execute: polymer build.
```
splem@debian:~/polymer-projects/polymer-project-template$ polymer build
info:    Building application...
info:    Generating build/unbundled...
info:    Generating build/bundled...
error:   Promise rejection: TypeError: Cannot read property 'map' of undefined
error:   TypeError: Cannot read property 'map' of undefined
    at Bundler._addSharedImportsToShell (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/lib/bundle.js:142:13)
    at /usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/lib/bundle.js:86:44
    at run (/usr/local/lib/node_modules/polymer-cli/node_modules/core-js/modules/es6.promise.js:87:22)
    at /usr/local/lib/node_modules/polymer-cli/node_modules/core-js/modules/es6.promise.js:100:28
    at flush (/usr/local/lib/node_modules/polymer-cli/node_modules/core-js/modules/_microtask.js:18:9)
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)
error:   Promise rejection: TypeError: Cannot read property 'map' of undefined
error:   TypeError: Cannot read property 'map' of undefined
    at Bundler._addSharedImportsToShell (/usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/lib/bundle.js:142:13)
    at /usr/local/lib/node_modules/polymer-cli/node_modules/polymer-build/lib/bundle.js:86:44
    at run (/usr/local/lib/node_modules/polymer-cli/node_modules/core-js/modules/es6.promise.js:87:22)
    at /usr/local/lib/node_modules/polymer-cli/node_modules/core-js/modules/es6.promise.js:100:28
    at flush (/usr/local/lib/node_modules/polymer-cli/node_modules/core-js/modules/_microtask.js:18:9)
    at nextTickCallbackWith0Args (node.js:452:9)
    at process._tickCallback (node.js:381:13)
```

I need help, thanks.

**Comment by FredKSchott** [comment]
Can you run `polymer build --verbose` and share the output?

**Comment by rof20004** [comment]
Thanks for answer, here is the verbose:

debug:   got args: 
{ args: [ 'build', '--verbose' ] }
debug:   got default config from file: 
{ config: 
   { entrypoint: 'index.html',
     shell: 'src/my-app.html',
     fragments: 
      [ 'src/my-contacts.html',
        'src/my-view2.html',
        'src/my-view3.html',
        'src/my-view404.html' ],
     sourceGlobs: [ 'src/**/*', 'images/**/*', 'bower.json' ],
     includeDependencies: 
      [ 'manifest.json',
        'bower_components/webcomponentsjs/webcomponents-lite.min.js' ] } }
debug:   adding command build
debug:   adding command help
debug:   adding command init
debug:   adding command lint
debug:   adding command serve
debug:   adding command test
debug:   running...
debug:   command 'build' found, parsing command args: 
{ args: [ '--verbose' ] }
debug:   command options parsed from args: 
{ 'sw-precache-config': 'sw-precache-config.js', verbose: true }
debug:   final project configuration generated: 
{ root: '/home/rof20004/polymer-projects/polymer-project-template',
  sourceGlobs: [ 'src/**/*', 'images/**/*', 'bower.json' ],
  includeDependencies: 
   [ 'manifest.json',
     'bower_components/webcomponentsjs/webcomponents-lite.min.js' ],
  entrypoint: '/home/rof20004/polymer-projects/polymer-project-template/index.html',
  shell: '/home/rof20004/polymer-projects/polymer-project-template/src/my-app.html',
  fragments: 
   [ '/home/rof20004/polymer-projects/polymer-project-template/src/my-contacts.html',
     '/home/rof20004/polymer-projects/polymer-project-template/src/my-view2.html',
     '/home/rof20004/polymer-projects/polymer-project-template/src/my-view3.html',
     '/home/rof20004/polymer-projects/polymer-project-template/src/my-view404.html' ],
  inputs: 
   [ '/home/rof20004/polymer-projects/polymer-project-template/index.html',
     '/home/rof20004/polymer-projects/polymer-project-template/src/my-app.html',
     '/home/rof20004/polymer-projects/polymer-project-template/src/my-contacts.html',
     '/home/rof20004/polymer-projects/polymer-project-template/src/my-view2.html',
     '/home/rof20004/polymer-projects/polymer-project-template/src/my-view3.html',
     '/home/rof20004/polymer-projects/polymer-project-template/src/my-view404.html' ] }
debug:   Running command...
debug:   building with options 
{ swPrecacheConfig: 'sw-precache-config.js',
  insertDependencyLinks: undefined,
  html: {},
  css: {},
  js: {} }
debug:   building via standard build()...
debug:   sourceGlobs: 
	/home/rof20004/polymer-projects/polymer-project-template/index.html
	/home/rof20004/polymer-projects/polymer-project-template/src/my-app.html
	/home/rof20004/polymer-projects/polymer-project-template/src/my-contacts.html
	/home/rof20004/polymer-projects/polymer-project-template/src/my-view2.html
	/home/rof20004/polymer-projects/polymer-project-template/src/my-view3.html
	/home/rof20004/polymer-projects/polymer-project-template/src/my-view404.html
	/home/rof20004/polymer-projects/polymer-project-template/src/**/*
	/home/rof20004/polymer-projects/polymer-project-template/images/**/*
	/home/rof20004/polymer-projects/polymer-project-template/bower.json
debug:   root: /home/rof20004/polymer-projects/polymer-project-template
debug:   shell: /home/rof20004/polymer-projects/polymer-project-template/src/my-app.html
debug:   entrypoint: /home/rof20004/polymer-projects/polymer-project-template/index.html
debug:   fragments: /home/rof20004/polymer-projects/polymer-project-template/src/my-contacts.html,/home/rof20004/polymer-projects/polymer-project-template/src/my-view2.html,/home/rof20004/polymer-projects/polymer-project-template/src/my-view3.html,/home/rof20004/polymer-projects/polymer-project-template/src/my-view404.html
debug:   sources: /home/rof20004/polymer-projects/polymer-project-template/src/**/*,/home/rof20004/polymer-projects/polymer-project-template/images/**/*,/home/rof20004/polymer-projects/polymer-project-template/bower.json
debug:   includeDependencies: /home/rof20004/polymer-projects/polymer-project-template/manifest.json,/home/rof20004/polymer-projects/polymer-project-template/bower_components/webcomponentsjs/webcomponents-lite.min.js
info:    Building application...
debug:   Reading source files...
debug:   sourceGlobs: 
	/home/rof20004/polymer-projects/polymer-project-template/index.html
	/home/rof20004/polymer-projects/polymer-project-template/src/my-app.html
	/home/rof20004/polymer-projects/polymer-project-template/src/my-contacts.html
	/home/rof20004/polymer-projects/polymer-project-template/src/my-view2.html
	/home/rof20004/polymer-projects/polymer-project-template/src/my-view3.html
	/home/rof20004/polymer-projects/polymer-project-template/src/my-view404.html
	/home/rof20004/polymer-projects/polymer-project-template/src/**/*
	/home/rof20004/polymer-projects/polymer-project-template/images/**/*
	/home/rof20004/polymer-projects/polymer-project-template/bower.json
debug:   Reading dependencies...
debug:   Service worker config found 
{ staticFileGlobs: 
   [ '/index.html',
     '/manifest.json',
     '/bower_components/webcomponentsjs/webcomponents-lite.min.js' ],
  navigateFallback: '/index.html' }
debug:   Analyzing build dependencies...
debug:   addFile: /home/rof20004/polymer-projects/polymer-project-template/index.html
info:    Generating build/unbundled...
info:    Generating build/bundled...
debug:   addFile: /home/rof20004/polymer-projects/polymer-project-template/manifest.json
debug:   addFile: /home/rof20004/polymer-projects/polymer-project-template/src/my-app.html
debug:   accept: src/my-app.html
debug:   addFile: /home/rof20004/polymer-projects/polymer-project-template/bower_components/webcomponentsjs/webcomponents-lite.min.js
debug:   addFile: /home/rof20004/polymer-projects/polymer-project-template/src/my-contacts.html
debug:   accept: src/my-contacts.html
debug:   addFile: /home/rof20004/polymer-projects/polymer-project-template/src/my-view2.html
debug:   accept: src/my-view2.html
debug:   addFile: /home/rof20004/polymer-projects/polymer-project-template/src/my-view3.html
debug:   accept: src/my-view3.html
debug:   addFile: /home/rof20004/polymer-projects/polymer-project-template/src/my-view404.html
debug:   accept: src/my-view404.html
debug:   addFile: /home/rof20004/polymer-projects/polymer-project-template/src/elements.html
debug:   addFile: /home/rof20004/polymer-projects/polymer-project-template/src/my-icons.html
debug:   addFile: /home/rof20004/polymer-projects/polymer-project-template/src/my-login.html
debug:   addFile: /home/rof20004/polymer-projects/polymer-project-template/src/shared-styles.html
debug:   addFile: /home/rof20004/polymer-projects/polymer-project-template/images/favicon.ico
debug:   addFile: /home/rof20004/polymer-projects/polymer-project-template/images/manifest/icon-144x144.png
debug:   addFile: /home/rof20004/polymer-projects/polymer-project-template/images/manifest/icon-192x192.png
debug:   addFile: /home/rof20004/polymer-projects/polymer-project-template/images/manifest/icon-48x48.png
debug:   addFile: /home/rof20004/polymer-projects/polymer-project-template/images/manifest/icon-512x512.png
debug:   addFile: /home/rof20004/polymer-projects/polymer-project-template/images/manifest/icon-72x72.png
debug:   addFile: /home/rof20004/polymer-projects/polymer-project-template/images/manifest/icon-96x96.png
debug:   addFile: /home/rof20004/polymer-projects/polymer-project-template/bower.json
error:   Promise rejection: TypeError: Cannot read property 'map' of undefined
error:   TypeError: Cannot read property 'map' of undefined
    at Bundler._addSharedImportsToShell (/usr/lib/node_modules/polymer-cli/node_modules/polymer-build/lib/bundle.js:142:13)
    at /usr/lib/node_modules/polymer-cli/node_modules/polymer-build/lib/bundle.js:86:44
    at run (/usr/lib/node_modules/polymer-cli/node_modules/core-js/modules/es6.promise.js:87:22)
    at /usr/lib/node_modules/polymer-cli/node_modules/core-js/modules/es6.promise.js:100:28
    at flush (/usr/lib/node_modules/polymer-cli/node_modules/core-js/modules/_microtask.js:18:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
error:   Promise rejection: TypeError: Cannot read property 'map' of undefined
error:   TypeError: Cannot read property 'map' of undefined
    at Bundler._addSharedImportsToShell (/usr/lib/node_modules/polymer-cli/node_modules/polymer-build/lib/bundle.js:142:13)
    at /usr/lib/node_modules/polymer-cli/node_modules/polymer-build/lib/bundle.js:86:44
    at run (/usr/lib/node_modules/polymer-cli/node_modules/core-js/modules/es6.promise.js:87:22)
    at /usr/lib/node_modules/polymer-cli/node_modules/core-js/modules/es6.promise.js:100:28
    at flush (/usr/lib/node_modules/polymer-cli/node_modules/core-js/modules/_microtask.js:18:9)
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
debug:   writing service worker... 
{ staticFileGlobs: 
   [ 'build/unbundled/index.html',
     'build/unbundled/manifest.json',
     'build/unbundled/bower_components/webcomponentsjs/webcomponents-lite.min.js',
     'build/unbundled/src/my-app.html',
     'build/unbundled/src/my-contacts.html',
     'build/unbundled/src/my-view2.html',
     'build/unbundled/src/my-view3.html',
     'build/unbundled/src/my-view404.html',
     'build/unbundled/index.html' ],
  navigateFallback: '/index.html',
  stripPrefix: 'build/unbundled',
  logger: [Function: bound _log] }
debug:   Total precache size is about 55.33 kB for 8 resources.

**Comment by rof20004** [comment]
If i remove this: 

<link rel="import" href="../bower_components/polymer/polymer.html">

from "elements.html" and place in each element that i created, it works, but not run polymer serve build/bundled, shows many errors.

**Comment by rof20004** [comment]
When I run polymer serve build/bundled shows this errors:

```
my-app.html:3 Uncaught NotSupportedError: Failed to execute 'registerElement' on 'Document': Registration failed for type 'dom-module'. A type with that name is already registered.(anonymous function) @ my-app.html:3(anonymous function) @ my-app.html:3
my-app.html:3 Uncaught TypeError: Polymer.Base._getExtendedPrototype is not a functiont @ my-app.html:3window.Polymer @ my-app.html:3(anonymous function) @ my-app.html:35(anonymous function) @ my-app.html:35
my-app.html:3 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ my-app.html:3t @ my-app.html:3window.Polymer @ my-app.html:3(anonymous function) @ my-app.html:149
my-app.html:3 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ my-app.html:3t @ my-app.html:3window.Polymer @ my-app.html:3(anonymous function) @ my-login.html:50
polymer.html:5 Uncaught TypeError: Cannot read property 'camelToDashCase' of undefined_addPropertyEffects @ polymer.html:5_prepBehavior @ polymer.html:7_prepFlattenedBehaviors @ polymer-micro.html:1_prepBehaviors @ polymer-micro.html:1_finishRegisterFeatures @ polymer.html:7_ensureRegisterFinished @ polymer-micro.html:1createdCallback @ polymer-micro.html:1
polymer.html:5 Uncaught TypeError: Cannot read property 'camelToDashCase' of undefined_addPropertyEffects @ polymer.html:5_prepBehavior @ polymer.html:7_prepFlattenedBehaviors @ polymer-micro.html:1_prepBehaviors @ polymer-micro.html:1_finishRegisterFeatures @ polymer.html:7_ensureRegisterFinished @ polymer-micro.html:1createdCallback @ polymer-micro.html:1instanceTemplate @ polymer-mini.html:5_stampTemplate @ polymer-mini.html:5_initFeatures @ my-app.html:35render @ polymer.html:7attached @ polymer.html:7_invokeBehavior @ polymer-micro.html:1_doBehavior @ polymer-micro.html:1(anonymous function) @ polymer-micro.html:1whenReady @ my-app.html:3attachedCallback @ polymer-micro.html:1attachedCallback @ polymer-mini.html:5_readySelf @ polymer-mini.html:5_ensureReady @ polymer.html:7_markImportsReady @ polymer.html:7(anonymous function) @ polymer.html:7_makeReady @ my-app.html:3(anonymous function) @ polymer-micro.html:1
polymer.html:5 Uncaught TypeError: Cannot read property 'node' of undefined
```

I moved the polymer.html to onlye one and global elements.html to solve this problem, but not generate build after that.

**Comment by robdodson** [comment]
Just curious, are you running this against an old version of PSK or a 2.x
version?

**Comment by rof20004** [comment]
@robdodson The 2.x version, you can clone my project, I use it only to study about webcomponents and polymer. I am using firebase too, for login and insert a contact.

1. git clone https://github.com/rof20004/polymer-project-template
2. bower install

Thanks for contacts

**Comment by robdodson** [comment]
You probably don't want to create an elements.html file. Have each element
import the things it depends on explicitly.

**Comment by rof20004** [comment]
@robdodson Ok, I will organize my imports and make some tests. Thanks for support =D. I will be back to talk about tests.

**Comment by rof20004** [comment]
Hi @robdodson , i organize all my imports to each element, localhost:8080 works perfect, but when i generate the build with polymer build, then run polymer serve build/bundled, shows many errors, i need to enter bundled and do 'bower install' to install paper-toast (i do not know why only this element not generate automatically in build), and after install paper-toast, when load the page shows this:

```
my-app.html:14 Uncaught NotSupportedError: Failed to execute 'registerElement' on 'Document': Registration failed for type 'dom-module'. A type with that name is already registered.(anonymous function) @ my-app.html:14(anonymous function) @ my-app.html:14
my-app.html:14 Uncaught TypeError: Polymer.Base._getExtendedPrototype is not a functiont @ my-app.html:14window.Polymer @ my-app.html:14(anonymous function) @ my-app.html:46(anonymous function) @ my-app.html:46
polymer-micro.html:1 Uncaught TypeError: Cannot read property 'camelToDashCase' of undefined_addPropertyInfo @ polymer-micro.html:1_prepPropertyInfo @ polymer-micro.html:1_finishRegisterFeatures @ polymer.html:7_ensureRegisterFinished @ polymer-micro.html:1createdCallback @ polymer-micro.html:1
my-app.html:14 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ my-app.html:14t @ my-app.html:14window.Polymer @ my-app.html:14(anonymous function) @ my-app.html:544(anonymous function) @ my-app.html:544
my-app.html:14 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ my-app.html:14t @ my-app.html:14window.Polymer @ my-app.html:14(anonymous function) @ my-app.html:700
my-app.html:14 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ my-app.html:14t @ my-app.html:14window.Polymer @ my-app.html:14(anonymous function) @ my-app.html:702(anonymous function) @ my-app.html:702
my-app.html:14 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ my-app.html:14t @ my-app.html:14window.Polymer @ my-app.html:14(anonymous function) @ my-app.html:723
my-app.html:14 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ my-app.html:14t @ my-app.html:14window.Polymer @ my-app.html:14(anonymous function) @ my-app.html:726
my-app.html:14 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ my-app.html:14t @ my-app.html:14window.Polymer @ my-app.html:14(anonymous function) @ my-app.html:1807
my-app.html:14 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ my-app.html:14t @ my-app.html:14window.Polymer @ my-app.html:14(anonymous function) @ my-app.html:1809
my-app.html:14 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ my-app.html:14t @ my-app.html:14window.Polymer @ my-app.html:14(anonymous function) @ my-app.html:1845
my-app.html:14 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ my-app.html:14t @ my-app.html:14window.Polymer @ my-app.html:14(anonymous function) @ my-app.html:1941
my-app.html:14 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ my-app.html:14t @ my-app.html:14window.Polymer @ my-app.html:14(anonymous function) @ my-app.html:2003
my-app.html:14 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ my-app.html:14t @ my-app.html:14window.Polymer @ my-app.html:14(anonymous function) @ my-app.html:2062
my-app.html:14 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ my-app.html:14t @ my-app.html:14window.Polymer @ my-app.html:14(anonymous function) @ my-app.html:2064(anonymous function) @ my-app.html:2064
my-app.html:14 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ my-app.html:14t @ my-app.html:14window.Polymer @ my-app.html:14(anonymous function) @ my-app.html:2065
my-app.html:14 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ my-app.html:14t @ my-app.html:14window.Polymer @ my-app.html:14(anonymous function) @ my-app.html:2074
my-app.html:14 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ my-app.html:14t @ my-app.html:14window.Polymer @ my-app.html:14(anonymous function) @ my-app.html:2076
my-app.html:14 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ my-app.html:14t @ my-app.html:14window.Polymer @ my-app.html:14(anonymous function) @ my-app.html:2095
my-app.html:14 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ my-app.html:14t @ my-app.html:14window.Polymer @ my-app.html:14(anonymous function) @ my-app.html:2098
my-app.html:14 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ my-app.html:14t @ my-app.html:14window.Polymer @ my-app.html:14(anonymous function) @ my-app.html:2146
my-app.html:14 Uncaught TypeError: this._desugarBehaviors is not a functionregisterCallback @ my-app.html:14t @ my-app.html:14window.Polymer @ my-app.html:14(anonymous function) @ my-app.html:2231
polymer.html:5 Uncaught TypeError: Cannot read property 'camelToDashCase' of undefined_addPropertyEffects @ polymer.html:5_prepBehavior @ polymer.html:7_prepFlattenedBehaviors @ polymer-micro.html:1_prepBehaviors @ polymer-micro.html:1_finishRegisterFeatures @ polymer.html:7_ensureRegisterFinished @ polymer-micro.html:1createdCallback @ polymer-micro.html:1
polymer.html:5 Uncaught TypeError: Cannot read property 'camelToDashCase' of undefined_addPropertyEffects @ polymer.html:5_prepBehavior @ polymer.html:7_prepFlattenedBehaviors @ polymer-micro.html:1_prepBehaviors @ polymer-micro.html:1_finishRegisterFeatures @ polymer.html:7_ensureRegisterFinished @ polymer-micro.html:1createdCallback @ polymer-micro.html:1instanceTemplate @ polymer-mini.html:5_stampTemplate @ polymer-mini.html:5_initFeatures @ my-app.html:46render @ polymer.html:7attached @ polymer.html:7_invokeBehavior @ polymer-micro.html:1_doBehavior @ polymer-micro.html:1(anonymous function) @ polymer-micro.html:1whenReady @ my-app.html:14attachedCallback @ polymer-micro.html:1attachedCallback @ polymer-mini.html:5_readySelf @ polymer-mini.html:5_ensureReady @ polymer.html:7_markImportsReady @ polymer.html:7(anonymous function) @ polymer.html:7_makeReady @ my-app.html:14(anonymous function) @ polymer-micro.html:1
polymer.html:5 Uncaught TypeError: Cannot read property 'node' of undefined
```

**Comment by robdodson** [comment]
Get rid of the <template is=dom-bind> and put everything including paper
toast and Polymerfire inside my-app. Make sure to include their imports in
my-app as well
On Sep 25, 2016 9:27 AM, "Rodolfo Azevedo" <notifications@github.com> wrote:

>

> Hi @robdodson <https://github.com/robdodson> , i organize all my imports
to each element, localhost:8080 works perfect, but when i generate the
build with polymer build, then run polymer serve build/bundled, shows many
errors, i need to enter bundled and do 'bower install' to install
paper-toast (i do not know why only this element not generate automatically
in build), and after install paper-toast, when load the page shows this:
>
> my-app.html:14 Uncaught NotSupportedError: Failed to execute
'registerElement' on 'Document': Registration failed for type 'dom-module'.
A type with that name is already registered.(anonymous function) @
my-app.html:14(anonymous function) @ my-app.html:14 my-app.html:14 Uncaught
TypeError: Polymer.Base._getExtendedPrototype is not a functiont @
my-app.html:14window.Polymer @ my-app.html:14(anonymous function) @
my-app.html:46(anonymous function) @ my-app.html:46 polymer-micro.html:1
Uncaught TypeError: Cannot read property 'camelToDashCase' of
undefined_addPropertyInfo @ polymer-micro.html:1_prepPropertyInfo @
polymer-micro.html:1_finishRegisterFeatures @
polymer.html:7_ensureRegisterFinished @ polymer-micro.html:1createdCallback
@ polymer-micro.html:1 my-app.html:14 Uncaught TypeError:
this._desugarBehaviors is not a functionregisterCallback @ my-app.html:14t
@ my-app.html:14window.Polymer @ my-app.html:14(anonymous function) @
my-app.html:544(anonymous function) @ my-app.html:544 my-app.html:14
Uncaught TypeError: this._desugarBehaviors is not a
functionregisterCallback @ my-app.html:14t @ my-app.html:14window.Polymer @
my-app.html:14(anonymous function) @ my-app.html:700 my-app.html:14
Uncaught TypeError: this._desugarBehaviors is not a
functionregisterCallback @ my-app.html:14t @ my-app.html:14window.Polymer @
my-app.html:14(anonymous function) @ my-app.html:702(anonymous function) @
my-app.html:702 my-app.html:14 Uncaught TypeError: this._desugarBehaviors
is not a functionregisterCallback @ my-app.html:14t @
my-app.html:14window.Polymer @ my-app.html:14(anonymous function) @
my-app.html:723 my-app.html:14 Uncaught TypeError: this._desugarBehaviors
is not a functionregisterCallback @ my-app.html:14t @
my-app.html:14window.Polymer @ my-app.html:14(anonymous function) @
my-app.html:726 my-app.html:14 Uncaught TypeError: this._desugarBehaviors
is not a functionregisterCallback @ my-app.html:14t @
my-app.html:14window.Polymer @ my-app.html:14(anonymous function) @
my-app.html:1807 my-app.html:14 Uncaught TypeError: this._desugarBehaviors
is not a functionregisterCallback @ my-app.html:14t @
my-app.html:14window.Polymer @ my-app.html:14(anonymous function) @
my-app.html:1809 my-app.html:14 Uncaught TypeError: this._desugarBehaviors
is not a functionregisterCallback @ my-app.html:14t @
my-app.html:14window.Polymer @ my-app.html:14(anonymous function) @
my-app.html:1845 my-app.html:14 Uncaught TypeError: this._desugarBehaviors
is not a functionregisterCallback @ my-app.html:14t @
my-app.html:14window.Polymer @ my-app.html:14(anonymous function) @
my-app.html:1941 my-app.html:14 Uncaught TypeError: this._desugarBehaviors
is not a functionregisterCallback @ my-app.html:14t @
my-app.html:14window.Polymer @ my-app.html:14(anonymous function) @
my-app.html:2003 my-app.html:14 Uncaught TypeError: this._desugarBehaviors
is not a functionregisterCallback @ my-app.html:14t @
my-app.html:14window.Polymer @ my-app.html:14(anonymous function) @
my-app.html:2062 my-app.html:14 Uncaught TypeError: this._desugarBehaviors
is not a functionregisterCallback @ my-app.html:14t @
my-app.html:14window.Polymer @ my-app.html:14(anonymous function) @
my-app.html:2064(anonymous function) @ my-app.html:2064 my-app.html:14
Uncaught TypeError: this._desugarBehaviors is not a
functionregisterCallback @ my-app.html:14t @ my-app.html:14window.Polymer @
my-app.html:14(anonymous function) @ my-app.html:2065 my-app.html:14
Uncaught TypeError: this._desugarBehaviors is not a
functionregisterCallback @ my-app.html:14t @ my-app.html:14window.Polymer @
my-app.html:14(anonymous function) @ my-app.html:2074 my-app.html:14
Uncaught TypeError: this._desugarBehaviors is not a
functionregisterCallback @ my-app.html:14t @ my-app.html:14window.Polymer @
my-app.html:14(anonymous function) @ my-app.html:2076 my-app.html:14
Uncaught TypeError: this._desugarBehaviors is not a
functionregisterCallback @ my-app.html:14t @ my-app.html:14window.Polymer @
my-app.html:14(anonymous function) @ my-app.html:2095 my-app.html:14
Uncaught TypeError: this._desugarBehaviors is not a
functionregisterCallback @ my-app.html:14t @ my-app.html:14window.Polymer @
my-app.html:14(anonymous function) @ my-app.html:2098 my-app.html:14
Uncaught TypeError: this._desugarBehaviors is not a
functionregisterCallback @ my-app.html:14t @ my-app.html:14window.Polymer @
my-app.html:14(anonymous function) @ my-app.html:2146 my-app.html:14
Uncaught TypeError: this._desugarBehaviors is not a
functionregisterCallback @ my-app.html:14t @ my-app.html:14window.Polymer @
my-app.html:14(anonymous function) @ my-app.html:2231 polymer.html:5
Uncaught TypeError: Cannot read property 'camelToDashCase' of
undefined_addPropertyEffects @ polymer.html:5_prepBehavior @
polymer.html:7_prepFlattenedBehaviors @ polymer-micro.html:1_prepBehaviors
@ polymer-micro.html:1_finishRegisterFeatures @
polymer.html:7_ensureRegisterFinished @ polymer-micro.html:1createdCallback
@ polymer-micro.html:1 polymer.html:5 Uncaught TypeError: Cannot read
property 'camelToDashCase' of undefined_addPropertyEffects @
polymer.html:5_prepBehavior @ polymer.html:7_prepFlattenedBehaviors @
polymer-micro.html:1_prepBehaviors @
polymer-micro.html:1_finishRegisterFeatures @
polymer.html:7_ensureRegisterFinished @ polymer-micro.html:1createdCallback
@ polymer-micro.html:1instanceTemplate @ polymer-mini.html:5_stampTemplate
@ polymer-mini.html:5_initFeatures @ my-app.html:46render @
polymer.html:7attached @ polymer.html:7_invokeBehavior @
polymer-micro.html:1_doBehavior @ polymer-micro.html:1(anonymous function)
@ polymer-micro.html:1whenReady @ my-app.html:14attachedCallback @
polymer-micro.html:1attachedCallback @ polymer-mini.html:5_readySelf @
polymer-mini.html:5_ensureReady @ polymer.html:7_markImportsReady @
polymer.html:7(anonymous function) @ polymer.html:7_makeReady @
my-app.html:14(anonymous function) @ polymer-micro.html:1 polymer.html:5
Uncaught TypeError: Cannot read property 'node' of undefined
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
<https://github.com/Polymer/polymer-build/issues/46#issuecomment-249431145>,
or mute the thread

**Comment by rof20004** [comment]
Thanks @robdodson I follow your tips and now it worked, in Chrome and Firefox without errors, running localhost with polymer serve and with polymer serve build/bundled.

The index file only have import to my-app (the main html), and each element import your dependencies.

Thanks @FredKSchott  about --verbose flag, I did not know that, helped me a lot to understand the messages.

I will now close this issue.

**Comment by rof20004** [comment]
teste
