### ISSUE TITLE
Reporting Build Errors

### ISSUE THREAD

**Issue by FredKSchott** [Polymer/polymer-build#58]
Because we analyze optimized code after `splitHtml()` & `rejoinHtml()` the warnings we get out of polymer-analyzer don't map 1:1 with the original source code. Minification makes the reported line numbers and code snippets useless.
#### Here's my plan for The World Of Today:
1. Analyze an entrypoint source file
2. If an exception is thrown, propagate it and throw (ending build)
3. If any warnings with severity ERROR exists on ANY documents, log those errors and exit
4. If any warnings with severity WARNING exists on any source documents, log it at the "warning" level and continue
5. If any warning with severity INFO exists on any source documents, log it at the "debug" level and continue
6. When printing warnings, only show the file name and hide the line numbers (will almost always be wrong). Hope that magnification/optimization doesn't create false-positive warning messages.
#### and for The World Of Tomorrow:
- Consider adding a special reporter that reports warnings at the end of your build pipeline instead of during, so that we can collect and report all warnings together
- Consider reporting warnings with correct source ranges via a first-pass linting step, or possibly by using source maps.

/cc @justinfagnani @rictic @usergenic

**Comment by justinfagnani** [comment]
Analyzing the original source is the right answer for now. If we want to allow weirder compile steps and push the warnings back through source maps we can do that later. For languages like TypeScript, we'll want the analyzer to handle that natively as it'll effect detecting properties and such.

As for error severities, if the analyzer doesn't crash I'd push forward with the build. During development it's useful to keep going even if there are missing files, syntax errors, etc.

**Comment by FredKSchott** [comment]
@justinfagnani agreed that during development it's useful to keep going, but that's not our goal with polymer-build, right? If we run into a serious error a build shouldn't continue.

Also can you clarify what you mean by original source? You mean the code that's currently being pushed into analyzer (after splitting and optimization), right? That's what's happening right now and is the only scenario that doesn't require significant refactoring.

**Comment by justinfagnani** [comment]
Build may be useful during development, say to test to bundled version or on IE. If an analyzer error happens, but it still produces output, why not? We can have a flag for strict build.

By original source, I mean the source read off disk, probably pre-splitting. That way any warnings relate to the files the user actually authored. This is what I thought you were talking about in the first sentence.

**Comment by FredKSchott** [comment]
I see the value in having an option to continue if it's technically possible, but if this is the default behavior we're going to have a lot of confused users ("my build succeeded but all I see is a gray screen?"). 

How about continuing with the build as far as possible, but exiting at the end of the build with an error code and log message if any errors were encountered? This would allow our users to go as far as possible with a build during development, but wouldn't hide the fact that their build is most likely bonked.

**Comment by justinfagnani** [comment]
They would have seen the gray screen in the unbuilt project as well, say if there's a resolution error like not finding a behavior. We can exit with a error code, but there's no reason I see to not emit the files if they can be.

**Comment by FredKSchott** [comment]
This was added in https://github.com/Polymer/polymer-build/pull/54
