### ISSUE TITLE
feature request: obfuscation tooling

### ISSUE THREAD

**Issue by joeblew99** [Polymer/polymer-build#66]
Supported obfuscation tools please ..

Anyone else want this ?

**Comment by FredKSchott** [comment]
Polymer-build lets you configure your own build pipeline, so there's nothing stopping you from adding javascript obfuscation to your own build. Take a look at https://www.npmjs.com/package/gulp-js-obfuscator and https://github.com/Polymer/polymer-build#projectsplithtml--projectrejoinhtml for help getting started
