### ISSUE TITLE
bundling step does not remove bundled dependencies from build directory, end up with both

### ISSUE THREAD

**Issue by FredKSchott** [Polymer/polymer-build#70]
See https://github.com/PolymerElements/polymer-starter-kit/issues/939

**Comment by usergenic** [comment]
Per in-person discussion today, `polymer-build` code should not simply pass-thru files through `BuildBundler` transform stream.  If we can obtain a manifest from bundler, we can filter out all of the inlined files from the original set and then pass-thru the rest after bundling.

**Comment by web-padawan** [comment]
Related to [this issue](https://github.com/Polymer/polymer/issues/4134#issuecomment-291501941)

**Comment by usergenic** [comment]
polymer-build 1.2.0 published :tada: includes this fix.
