### ISSUE TITLE
Silent build failure when importing not-existing file

### ISSUE THREAD

**Issue by web-padawan** [Polymer/polymer-build#88]
Occasionally forgotten import of file which has been deleted caused this for me: 

### Description
```
init_1   | [06:45:38] Starting 'vulcanize'...
init_1   | [06:45:50] The following tasks did not complete: default, vulcanize
init_1   | [06:45:50] Did you forget to signal async completion?
```

Gulp task looks like this:

```
const errorHandler = function (err) {
    // exit with a 'failure' code on build errors
    console.error(err.message);
    process.exit(1);
};

// Vulcanize components, generate shared file
function vulcanize () {
    return merge(project.sources(), project.dependencies())
        .pipe(project.analyzer)
        .on('error', errorHandler)
        .pipe(project.bundler)
        .on('error', errorHandler)
        .pipe(gulp.dest(TMP));
}
```

### Versions & Environment
- polymer-build: 0.5.1
- node: 6.9.1
- Operating System: Mac Os X El capitan

#### Expected Results
An error should be thrown (e. g. `Error: file ... does not exist`)

#### Actual Results
Build fails with no errors and 0 exit code.

**Comment by FredKSchott** [comment]
Can you try on `v0.6.0.alpha.1`? I had thought we'd fixed this in the latest version but it may still be hanging around. If so we should get to this ASAP

**Comment by tony19** [comment]
This issue still occurs with `v0.6.0`.

**Comment by FredKSchott** [comment]
thanks for following up @tony19.

Alright, we should fix this asap. Hanging on builds and having to track down broken imports yourself is just silly.

**Comment by tony19** [comment]
### Steps to reproduce:

 1. Create directory, CD into it, and run `polymer init starter-kit` (which creates PSK 2.1.1)
 2. Edit `src/my-icons.html` to import a non-existing `iron-iconset-svg.html`.
 3. Run `polymer build`.
 4. Observe it does not complete, and silently exits with code 0.

The interesting thing is if you move all files into a subdirectory of `src/`, `polymer build` correctly emits an error:

 5. Move `src/*.html` into `src/components`, and rebuild:

        mkdir src/components
        mv src/*.html src/components/.
        sed -i '' 's%src/%src/components/%g' polymer.json
        polymer build

   <details>
    <summary>resulting <code>polymer.json</code></summary>
<pre>{
  "entrypoint": "index.html",
  "shell": "src/components/my-app.html",
  "fragments": [
    "src/components/my-view1.html",
    "src/components/my-view2.html",
    "src/components/my-view3.html",
    "src/components/my-view404.html"
  ],
  "sourceGlobs": [
    "src/components/**/*",
    "images/**/*",
    "bower.json"
  ],
  "includeDependencies": [
    "manifest.json",
    "bower_components/webcomponentsjs/webcomponents-lite.min.js"
  ]
}</pre>
   </details>

 6. Observe an error (correct behavior):

        $ polymer build
        info:    Preparing build...
        info:    Building application...
        info:    Generating build/unbundled...
        info:    Generating build/bundled...
        error:   Uncaught exception: Error: ENOENT: no such file or directory, open '/Users/tony/src/polymer/tmp/psk2/src/bower_components/polymer/polymer.html'
        error:   Error: ENOENT: no such file or directory, open '/Users/tony/src/polymer/tmp/psk2/src/bower_components/polymer/polymer.html'

**Comment by FredKSchott** [comment]
@tony19 Interesting, doing as you said and adding this import with it's leading `../` removed resulted in the silent failure you saw:
```
<link rel="import" href="bower_components/this-is-not/a-pipe.html">
```

But adding a bad import that still has its leading `../` leads to the correct "no such file" error:
```
<link rel="import" href="../bower_components/this-is-not/a-pipe.html">
```

**Comment by FredKSchott** [comment]
So this is happening because removing the leading slash places it in the `src` directory, which build treats as a 'source' file and not a 'dependency'. We load your sources based on the `sources` globs defined in your polymer.json, which means that the analyzer is saying "oh this is a source file, I'll just wait for it to come in via the source glob loader". When it never comes in (because it does not exist) everything just exits.

**Comment by tony19** [comment]
Here's a GitHub project to reproduce the issue: https://github.com/tony19-sandbox/polymer-build-issue-88

**Comment by tony19** [comment]
@FredKSchott I updated the [repro](https://github.com/tony19-sandbox/polymer-build-issue-88) with `polymer-cli` 0.18.0-alpha.9 and `polymer-build` 0.7.0, and the silent failure still occurs (locally and in [Travis](https://travis-ci.org/tony19-sandbox/polymer-build-issue-88/builds/197205475)). Can this issue be reopened? Or should I create a new issue?

**Comment by FredKSchott** [comment]
@tony19 okay lets take a look at your more complex app in a separate issue, mind creating one? 

FWIW I still can't reproduce locally with the latest polymer-build. (I see: `Error: ENOENT: no such file or directory, open '/Users/fschott/Code/polymer-build-issue-88/bower_components/neon-animation/neon-animated-pages.html'`).

**Comment by tony19** [comment]
@FredKSchott Ok, created #119.
