### ISSUE TITLE
How to add a custom task to polymer-build

### ISSUE THREAD

**Issue by biaggi** [Polymer/polymer-build#95]
Hi all :)

I've been searching all over internet to try to understand how to use polymer-cli / polymer-build. 

I've found a couple places in which people says that you have a "basic" pipeline already contained in polymer-cli, but if you want to add some custom task, you are somehow obliged to use polymer-build.

I've seen the provided example, but I cannot figure out where should be located such piece of code or how to execute the building pipeline using polymer-buid.

I think that I did not understood something basic, for now my conclusion is that I should be modifying the project gulpfile, so my point is that I dont really need polymer-build to do so.

What part am I misunderstanding?

Regards

**Comment by justinfagnani** [comment]
Hi @biaggi, it doesn't sound like you're really missing anything. Using `polymer-build` directly in a gulpfile is indeed what you need to do if you want to customize your build pipeline outside of the flags offered by the Polymer CLI.

The general idea is that we can't accommodate all of the possible needs of an apps build pipeline, so we need to offer a fully customizable solution like `polymer-build`. Once that's at least viable for people we can work on filling gaps between polymer-cli and polymer-build, knowing that if the CLI can't do something yet, at least people aren't actually blocked.

As for where in the pipeline you insert your own tasks, it depends on the task. Generally you'd have a setup that mirrors what the CLI does, but inserts tasks, possibly only for your own project's sources:

```typescript
import {PolymerProject} from 'polymer-build';
const mergeStream = require('merge-stream');

const project = new PolymerProject({
  entrypoint: 'index.html',
  shell: 'src/my-app.html',
  fragments: [
    'src/my-view1.html',
    'src/my-view2.html',
  ],
});

const sources = project.sources()
  .pipe(myTransform()) // These transforms only effect your sources, not dependencies
  .pipe(myOtherTransform())

const allFiles = mergeStream(sources, project.dependencies())
  .pipe(gulp.dest('build/'));
```

We should have more complete examples here to help. I added #96 to track that.

**Comment by biaggi** [comment]
Thanks for your clarification @justinfagnani
 
I was expecting to find something plugable, agree with the more complete examples, maybe an official generator for polymer-cli would do the trick.

**Comment by FredKSchott** [comment]
@biaggi you can check out https://github.com/PolymerElements/generator-polymer-init-custom-build as well for an example of a project using and configuring its own polymer-build setup.
